//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niagapos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public string TransactionDetailId { get; set; }
        public string TransactionId { get; set; }
        public string ProductId { get; set; }
        public int PurchaseTotal { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> Disc { get; set; }
        public decimal Total { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
